version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    user: "mysql:mysql"
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  wordpress:
    image: wordpress:latest
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - db
      - redis
    volumes:
      - ./wordpress_data:/var/www/html
      - ${PWD}/wp-config.php:/var/www/html/wp-config.php
    # ports:
    #   - "8001:80" # we dont need to publish this port, because it will automatically expose container port in ip container
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      backend:
      dockervlan:
        ipv4_address: "10.55.254.33" # ip address static for container wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8011:80" # need define this port to expose pma in dockerhost
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - backend

  redis:
    image: redis
    restart: always
    container_name: redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    # ports: # this is optional to expose redis
    #   - "6379:6379"
    entrypoint: redis-server --maxmemory 512mb
    networks:
      - backend

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  backend:
    driver : bridge

  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.55.254.0/24" # prefix network in your lan
          ip_range: "10.55.254.32/27" # ip address pool available for container will be join in macvlan network 
          gateway: "10.55.254.254" # gateway network in your lan