version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    user: "mysql:mysql"
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # networks:
    #   - dockervlan
      # dockervlan:
      #   ipv4_address: 10.55.254.36

  wordpress:
    image: wordpress:latest
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - db
      - redis
    #image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
      - ${PWD}/wp-config.php:/var/www/html/wp-config.php
    ports:
      - "8001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    # networks:
    #   - dockervlan
      # dockervlan:
      #   ipv4_address: 10.55.254.35

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8011:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress

  redis:
    image: redis
    restart: always
    container_name: redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "6379:6379"
    # launch Redis in cache mode with :
    #  - max memory up to 50% of your RAM if needed (--maxmemory 512mb)
    #  - deleting oldest data when max memory is reached (--maxmemory-policy allkeys-lru)
    # entrypoint: redis-server --maxmemory 512mb -maxmemory-policy allkeys-lru
    entrypoint: redis-server --maxmemory 512mb

volumes:
  db_data: {}
  wordpress_data: {}

# networks:
#   dockervlan:
#     name: dockervlan
#     driver: macvlan
#     driver_opts:
#       parent: eth0
#     ipam:
#       config:
#         - subnet: "10.55.254.0/24"
#           ip_range: "10.55.254.32/27"
#           gateway: "10.55.254.254"